### ISSUE TITLE
Программа не запускается

### ISSUE THREAD

**Issue by griale46** [QualitySolution/Bazar#43]
Добрый день ,скачали версию bazar-2.4, установили, но программа не запускается вообще.
ОС Win10x64

В журнале следующая информация
Application Error
Имя сбойного приложения: BazAr.exe, версия: 2.4.0.0, метка времени: 0x5e170023
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.18362.535, метка времени: 0x5bd9df62
Код исключения: 0xe0434352
Смещение ошибки: 0x001135d2
Идентификатор сбойного процесса: 0x1f8c
Время запуска сбойного приложения: 0x01d5cd0305b9531d
Путь сбойного приложения: C:\Program Files (x86)\Базар\BazAr.exe
Путь сбойного модуля: C:\Windows\System32\KERNELBASE.dll
Идентификатор отчета: 8b2e29ad-3fcb-47eb-869c-36798c5bcd91
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
и
.NET Runtime
Приложение: BazAr.exe
Версия платформы: v4.0.30319
Описание. Процесс был завершен из-за необработанного исключения.
Сведения об исключении: System.IO.FileNotFoundException
   в Bazar.MainClass.Main(System.String[])

**Comment by Gankov** [comment]
Первым делом после установки попробуйте пререзагрузить компьютер. Иногда помогает.
Вообще воспользуйтесь проверьте установлена ли библиотека Gtk# можно воспользоваться инструкцие http://workwear.qsolution.ru/?page_id=435 для проверки.
Если нет скачайте и установите https://xamarin.azureedge.net/GTKforWindows/Windows/gtk-sharp-2.12.21.msi вручную.
